### ISSUE TITLE
✨ Add labels to LocalizeSelect

### ISSUE THREAD

**Issue by johannchopin** [Lyokolux/ux-typing-experiment#21]
Currently `LocalizeSelect` show the `value` like:

![image](https://user-images.githubusercontent.com/31794680/134483328-5e652112-19a0-42bc-bff2-78c8a4af6064.png)

Better would be to see:

- `English`
- `Français`
- `Deutsch`

**Comment by johannchopin** [comment]
@ibrahimlahouar We could do that together as a first step with svelte 😉

**Comment by ibrahimlahouar** [comment]
I will
Le dim. 26 sept. 2021 à 14:59, johannchopin ***@***.***> a
écrit :
