### ISSUE TITLE
✨ Store user infos in firestore

### ISSUE THREAD

**Issue by johannchopin** [Lyokolux/ux-typing-experiment#22]
Send data from `UserInfos` to firestore.

**Comment by Lyokolux** [comment]
More specs:

* In a /store/api.ts, two request `addUserRequest` and `addExperimentRequest` should be available to the pages.
* The logic behind that handles documents and these sort of stuff in firebase should not be exposed in the component and at least stored in the api.ts or in a dedicated module if needed.

@johannchopin an idea about the name of the method calling each request ?
