### ISSUE TITLE
✨ Button component with loading animation

### ISSUE THREAD

**Issue by johannchopin** [Lyokolux/ux-typing-experiment#53]
Add `Button` component with `isLoading` prop that show a loader and hide the text.

- it should show a spinner https://getbootstrap.com/docs/5.0/components/spinners/ in the middle of the button and hide the text
- the button shouldn't resize on making the transition `normal --> loading` --> use `position: absolute`

**Comment by Lyokolux** [comment]
@johannchopin you can **link** your PR on the right of an issue. Is merged so close it.
