### ISSUE TITLE
🗃️ Send experience's configs and events to firestore

### ISSUE THREAD

**Issue by johannchopin** [Lyokolux/ux-typing-experiment#55]
In the `Experience` component there is an `onFilled` callback. When triggered, the data `displayChunkLength`
and `inputChunkLength` should be stored in association with the `events`.

The `Experience` interface for the data could be smthg like:

```ts
import type { Event } from 'src/components/AlphanumericInput/utils'

interface Experience {
  displayChunkLength: number
  inputChunkLength: number
  events: Event[]
}
```

Another idea could be to store the  `displayChunkLength` and `inputChunkLength` as a key that could be generated by using `{displayChunkLength}-{inputChunkLength}` like `"2-18"` and that contains all the `events` like:

```ts
import type { Event } from 'src/components/AlphanumericInput/utils'

interface Experiences {
  '2-18': Event[]
  '4-18': Event[]
  // ...
}
```

The advantages are that it consumes less MiB and it will be easier to get a specify config for an experiment.

**Comment by Lyokolux** [comment]
I would go for the second idea
