### ISSUE TITLE
✨ Add a property to user depending of the device he is using

### ISSUE THREAD

**Issue by Lyokolux** [Lyokolux/ux-typing-experiment#66]
A user won't type at the same speed on Desktop, Tablet or Smartphone. Thus we need to distinguish the device used for the experiments.
This value will be then sent and stored with the user informations (in the `addUserRequest`).

1. Extend the interface `User` as follow with a property `device` which holds the value of the different device possible: Desktop, Tablet and Smartphone. 
2. Detect the device via a util function `getDeviceName`
3. Retrieve this value just in time before sending the request

**Comment by johannchopin** [comment]
@Lyokolux  You can direcly use the `$screen.isMobile` store's method.

**Comment by Lyokolux** [comment]
> @Lyokolux You can direcly use the `$screen.isMobile` store's method.

So we reduce the possibility to Mobile or other device ?

**Comment by Lyokolux** [comment]
> > @Lyokolux You can direcly use the `$screen.isMobile` store's method.
> 
> So we reduce the possibility to Mobile or other device ?

For now yes

**Comment by Lyokolux** [comment]
Merged
