### ISSUE TITLE
🐛 On first load, the first view is not properly displayed for a short period of time

### ISSUE THREAD

**Issue by Lyokolux** [Lyokolux/ux-typing-experiment#72]
![Screenshot from 2021-10-01 14-38-50](https://user-images.githubusercontent.com/29046067/135620931-e14b4b7b-f493-4724-8b00-77a76550c04b.png)

Adding a loader can solve this. Any other ideas ? @johannchopin @flololan @ibrahimlahouar

**Comment by johannchopin** [comment]
@Lyokolux did you tried with the builded website?

**Comment by Lyokolux** [comment]
The URL is https://ux-typing-experiment-qgkzmlxpd-lyokolux.vercel.app/

**Comment by johannchopin** [comment]
@Lyokolux A loading screen is a nice idea 👍 Smthg like the firestore dashboard
