### ISSUE TITLE
🥅 Handle requests failure

### ISSUE THREAD

**Issue by johannchopin** [Lyokolux/ux-typing-experiment#73]
Try catch all requests and show a modal if error

**Comment by johannchopin** [comment]
Not sure how to locally test that since not network isn't an error for firestore

**Comment by Lyokolux** [comment]
> Not sure how to locally test that since no~t~ network isn't an error for firestore

Change your credentials in the firestore config file ?

**Comment by johannchopin** [comment]
@Lyokolux  I Can take care of it 👍

**Comment by johannchopin** [comment]
If credentials are wrong the app crash during the ssr time so there is no real risks here so let's close this topic.
