### ISSUE TITLE
💄 Design of the radio buttons

### ISSUE THREAD

**Issue by Lyokolux** [Lyokolux/ux-typing-experiment#76]
V1: background transparent, larger border
![Screenshot from 2021-10-01 18-12-05](https://user-images.githubusercontent.com/29046067/135654126-463d5af5-06f9-4439-adea-20d8c56d3273.png)

V2: border color → primary color, box 20% bigger
![Screenshot from 2021-10-01 18-18-06](https://user-images.githubusercontent.com/29046067/135654198-f1edb74a-804a-4f8b-ad93-1a1abccf23fa.png)

**Comment by Lyokolux** [comment]
What do you think of it @johannchopin @flololan @ibrahimlahouar

**Comment by johannchopin** [comment]
Nice
