### ISSUE TITLE
✨ Screen 3: familiarization screen

### ISSUE THREAD

**Issue by Lyokolux** [Lyokolux/ux-typing-experiment#8]
See https://guillaumegronier.com/2021-mi/styled-39/index.html

**Comment by johannchopin** [comment]
@Lyokolux Where is the PR for this one? Because it's in the `PR Review` column.

**Comment by Lyokolux** [comment]
> @Lyokolux Where is the PR for this one? Because it's in the `PR Review` column.

The PR is already merged. So this issue can be closed.
