### ISSUE TITLE
🐛  Form validation feedback is wrong

### ISSUE THREAD

**Issue by Lyokolux** [Lyokolux/ux-typing-experiment#89]
1. appears to late (regression from #83 )
2. provide gibberish explanations

![Screenshot from 2021-10-05 23-48-12](https://user-images.githubusercontent.com/29046067/136107608-43b959fd-a241-4c23-beb1-25841ed04ac5.png)

**Comment by Lyokolux** [comment]
Actually we won't need it as the next button will only appear when the form is correctly filled

**Comment by johannchopin** [comment]
Is that still relevant? Should we close it?

**Comment by Lyokolux** [comment]
Not relevant anymore as these errors are not possible anymore by a non-malicious user
